### ISSUE TITLE
Issue; Redundant Code

### ISSUE THREAD

**Issue by Scherso** [KnightsWhoSayNi0/discordArchiveBot#4]
You should remove all redundant code; ie. All of it. 👍

**Comment by KnightsWhoSayNi0** [comment]
I could improve the efficiency of this so much, but I don't have the time and I'm just too lazy to lnao

**Comment by Scherso** [comment]
damn you didnt need to bash yourself like that bro

**Comment by Scherso** [comment]
hi, I would like to bring this issue back up, delete this repository, now.

**Comment by KnightsWhoSayNi0** [comment]
:)
